trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  repositoryName: 'andreitalkun/azurepipelines' 

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: $(repositoryName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'